import type { ComponentType } from "react";

import {
  AdminShieldIcon,
  BellIcon,
  BuildingIcon,
  CalendarCheckIcon,
  ClipboardIcon,
  ClockIcon,
  CodeIcon,
  DownloadIcon,
  FileCheckIcon,
  FileTextIcon,
  GlobeIcon,
  LinkIcon,
  MailIcon,
  MobileIcon,
  PaintIcon,
  PercentageIcon,
  PricingIcon,
  RewardIcon,
  SearchIcon,
  ShieldCheckIcon,
  StarIcon,
  StoreIcon,
  TagIcon,
  TerminalIcon,
  TruckIcon,
} from "@louez/ui/icons";

export type SettingsNavigationGroupId = "store" | "rental" | "communication" | "accountData";

export type SettingsNavigationItem = {
  descriptionPath: string;
  group: SettingsNavigationGroupId;
  href: string;
  icon: ComponentType<{ className?: string }>;
  id: string;
  labelPath: string;
  navigation: boolean;
  platformAdminOnly?: boolean;
  /** Hidden unless the store's electronic-invoicing rollout flag is on. */
  requiresElectronicInvoicing?: boolean;
  searchPaths: string[];
};

export const SETTINGS_NAVIGATION_GROUPS: SettingsNavigationGroupId[] = [
  "store",
  "rental",
  "communication",
  "accountData",
];

export const SETTINGS_NAVIGATION_ITEMS: SettingsNavigationItem[] = [
  // The public site is edited in its own full-screen editor; this entry opens it.
  {
    id: "online-store",
    href: "/online-store",
    icon: StoreIcon,
    labelPath: "dashboard.navigation.onlineStore",
    descriptionPath: "dashboard.onlineStore.description",
    searchPaths: ["dashboard.onlineStore.sections"],
    group: "store",
    navigation: true,
  },
  {
    id: "store",
    href: "/dashboard/settings",
    icon: BuildingIcon,
    labelPath: "dashboard.settings.company",
    descriptionPath: "dashboard.settings.companySettings.description",
    searchPaths: ["dashboard.settings.storeSettings", "dashboard.settings.billingAddress"],
    group: "store",
    navigation: true,
  },
  // The storefront pages are edited in the full-screen online store editor.
  // They stay listed, out of the nav, so the settings search still leads there.
  {
    id: "appearance",
    href: "/online-store/identity",
    icon: PaintIcon,
    labelPath: "dashboard.settings.appearance",
    descriptionPath: "dashboard.settings.appearanceSettings.description",
    searchPaths: ["dashboard.settings.appearanceSettings"],
    group: "store",
    navigation: false,
  },
  {
    id: "marketplace",
    href: "/dashboard/settings/marketplace",
    icon: GlobeIcon,
    labelPath: "dashboard.settings.salesChannels.title",
    descriptionPath: "dashboard.settings.salesChannels.description",
    searchPaths: ["dashboard.settings.salesChannels"],
    group: "store",
    navigation: true,
  },
  {
    id: "hours",
    href: "/dashboard/settings/hours",
    icon: ClockIcon,
    labelPath: "dashboard.settings.hours",
    descriptionPath: "dashboard.settings.businessHours.navDescription",
    searchPaths: ["dashboard.settings.businessHours"],
    group: "store",
    navigation: true,
  },
  {
    id: "contact",
    href: "/online-store/contact",
    icon: MailIcon,
    labelPath: "dashboard.settings.contact",
    descriptionPath: "dashboard.settings.contactSettings.description",
    searchPaths: ["dashboard.settings.contactSettings"],
    group: "store",
    navigation: false,
  },
  {
    id: "legal",
    href: "/online-store/legal",
    icon: FileTextIcon,
    labelPath: "dashboard.settings.legal",
    descriptionPath: "dashboard.settings.legalSettings.description",
    searchPaths: ["dashboard.settings.legalSettings"],
    group: "store",
    navigation: false,
  },
  {
    id: "seo",
    href: "/online-store/seo",
    icon: SearchIcon,
    labelPath: "dashboard.settings.seo",
    descriptionPath: "dashboard.settings.seoSettings.description",
    searchPaths: ["dashboard.settings.seoSettings"],
    group: "store",
    navigation: false,
  },
  {
    id: "reservations",
    href: "/dashboard/settings/reservations",
    icon: CalendarCheckIcon,
    labelPath: "dashboard.settings.reservationRules",
    descriptionPath: "dashboard.settings.reservationSettings.description",
    searchPaths: ["dashboard.settings.reservationSettings", "dashboard.settings.extensions"],
    group: "rental",
    navigation: true,
  },
  {
    id: "payments",
    href: "/dashboard/settings/payments",
    icon: PricingIcon,
    labelPath: "dashboard.settings.payments.title",
    descriptionPath: "dashboard.settings.payments.description",
    searchPaths: ["dashboard.settings.payments"],
    group: "rental",
    navigation: true,
  },
  {
    id: "taxes",
    href: "/dashboard/settings/taxes",
    icon: PercentageIcon,
    labelPath: "dashboard.settings.taxes.title",
    descriptionPath: "dashboard.settings.taxes.description",
    searchPaths: ["dashboard.settings.taxes"],
    group: "rental",
    navigation: true,
  },
  {
    id: "invoicing",
    href: "/dashboard/settings/invoicing",
    icon: FileCheckIcon,
    labelPath: "dashboard.settings.invoicing.title",
    descriptionPath: "dashboard.settings.invoicing.description",
    searchPaths: ["dashboard.settings.invoicing"],
    requiresElectronicInvoicing: true,
    group: "rental",
    navigation: true,
  },
  {
    id: "delivery",
    href: "/dashboard/settings/delivery",
    icon: TruckIcon,
    labelPath: "dashboard.settings.delivery.title",
    descriptionPath: "dashboard.settings.delivery.description",
    searchPaths: ["dashboard.settings.delivery"],
    group: "rental",
    navigation: true,
  },
  {
    id: "inspections",
    href: "/dashboard/settings/inspections",
    icon: ClipboardIcon,
    labelPath: "dashboard.settings.inspection.title",
    descriptionPath: "dashboard.settings.inspection.description",
    searchPaths: ["dashboard.settings.inspection"],
    group: "rental",
    navigation: true,
  },
  {
    id: "promo-codes",
    href: "/dashboard/settings/promo-codes",
    icon: TagIcon,
    labelPath: "dashboard.settings.promoCodes.title",
    descriptionPath: "dashboard.settings.promoCodes.description",
    searchPaths: ["dashboard.settings.promoCodes"],
    group: "rental",
    navigation: true,
  },
  {
    id: "notifications",
    href: "/dashboard/settings/notifications",
    icon: BellIcon,
    labelPath: "dashboard.settings.notifications.title",
    descriptionPath: "dashboard.settings.notifications.description",
    searchPaths: ["dashboard.settings.notifications"],
    group: "communication",
    navigation: true,
  },
  {
    id: "review-booster",
    href: "/dashboard/settings/review-booster",
    icon: StarIcon,
    labelPath: "dashboard.settings.reviewBooster.title",
    descriptionPath: "dashboard.settings.reviewBooster.description",
    searchPaths: ["dashboard.settings.reviewBooster"],
    group: "communication",
    navigation: true,
  },
  {
    id: "integrations",
    href: "/dashboard/settings/integrations",
    icon: LinkIcon,
    labelPath: "dashboard.settings.integrations",
    descriptionPath: "dashboard.settings.integrationsPage.description",
    searchPaths: ["dashboard.settings.integrationsPage", "dashboard.settings.integrationsHub"],
    group: "communication",
    navigation: true,
  },
  {
    id: "referrals",
    href: "/dashboard/settings/referrals",
    icon: RewardIcon,
    labelPath: "dashboard.settings.referrals",
    descriptionPath: "dashboard.referrals.description",
    searchPaths: ["dashboard.referrals"],
    group: "communication",
    navigation: true,
  },
  {
    id: "widget",
    href: "/dashboard/settings/integrations/widget",
    icon: MobileIcon,
    labelPath: "dashboard.settings.integrationsHub.builtIn.widget.name",
    descriptionPath: "dashboard.settings.integrationsHub.builtIn.widget.description",
    searchPaths: ["dashboard.settings.embed", "dashboard.settings.integrationsHub.builtIn.widget"],
    group: "communication",
    navigation: false,
  },
  {
    id: "mcp",
    href: "/dashboard/settings/integrations/mcp",
    icon: TerminalIcon,
    labelPath: "dashboard.settings.integrationsHub.builtIn.mcp.name",
    descriptionPath: "dashboard.settings.integrationsHub.builtIn.mcp.description",
    searchPaths: ["dashboard.settings.api", "dashboard.settings.integrationsHub.builtIn.mcp"],
    group: "communication",
    navigation: false,
  },
  {
    id: "api",
    href: "/dashboard/settings/integrations/api",
    icon: CodeIcon,
    labelPath: "dashboard.settings.integrationsHub.builtIn.api.name",
    descriptionPath: "dashboard.settings.integrationsHub.builtIn.api.description",
    searchPaths: ["dashboard.settings.api", "dashboard.settings.integrationsHub.builtIn.api"],
    group: "communication",
    navigation: false,
  },
  {
    id: "google-calendar",
    href: "/dashboard/settings/integrations/google-calendar",
    icon: LinkIcon,
    labelPath: "dashboard.settings.integrationsHub.providers.googleCalendar.name",
    descriptionPath: "dashboard.settings.integrationsHub.providers.googleCalendar.description",
    searchPaths: [
      "dashboard.settings.integrationsHub.categories.calendar",
      "dashboard.settings.integrationsHub.providers.googleCalendar",
    ],
    group: "communication",
    navigation: false,
  },
  {
    id: "ics-calendar",
    href: "/dashboard/settings/integrations/ics-calendar",
    icon: LinkIcon,
    labelPath: "dashboard.settings.integrationsHub.providers.icsCalendar.name",
    descriptionPath: "dashboard.settings.integrationsHub.providers.icsCalendar.description",
    searchPaths: [
      "dashboard.settings.integrationsHub.categories.calendar",
      "dashboard.settings.integrationsHub.providers.icsCalendar",
    ],
    group: "communication",
    navigation: false,
  },
  {
    id: "tulip",
    href: "/dashboard/settings/integrations/tulip",
    icon: ShieldCheckIcon,
    labelPath: "dashboard.settings.integrationsHub.providers.tulip.name",
    descriptionPath: "dashboard.settings.integrationsHub.providers.tulip.description",
    searchPaths: [
      "dashboard.settings.integrationsHub.providers.tulip",
      "dashboard.settings.integrationsPage.assurance",
    ],
    group: "communication",
    navigation: false,
  },

  {
    id: "export",
    href: "/dashboard/settings/export",
    icon: DownloadIcon,
    labelPath: "dashboard.settings.export.title",
    descriptionPath: "dashboard.settings.export.description",
    searchPaths: ["dashboard.settings.export"],
    group: "accountData",
    navigation: true,
  },
  {
    id: "admin",
    href: "/dashboard/settings/admin",
    icon: AdminShieldIcon,
    labelPath: "dashboard.settings.admin.title",
    descriptionPath: "dashboard.settings.admin.description",
    searchPaths: ["dashboard.settings.admin"],
    group: "accountData",
    navigation: true,
    platformAdminOnly: true,
  },
];
